/** @format */

// Persistent object cache for avoiding recompilation of identical child objects.
// Content-addressed storage: SHA-256(preprocessed_source + overrides + compiler_version
//                                    + enable_debug + cache_format_version)
//
// On-disk layout per entry (key = SHA-256 hex):
//   <key>.bin  — compiled child binary (load-bearing)
//   <key>.sym  — serialized user symbols for map file generation (load-bearing,
//                read only when writeMapFile is enabled)
//   <key>.dbg  — serialized debug records contributed by this child (load-
//                bearing whenever the cached .bin contains BRK opcodes; only
//                ever produced when --debug was on at store time)
//   <key>.meta — human-readable JSON diagnostic (optional, never required by
//                the hit path)
//
// Why .dbg exists: each debug() call bakes a brkCode (an index into the
// compile's shared DebugData table) into the child's binary. The actual
// records — format strings + on-device debugger commands — live only in that
// table, which is rebuilt from scratch every compile. Without restoring the
// child's records on cache hit, the brkCodes in the cached .bin alias to
// whatever the new compile happened to put at those indices, producing
// nonsense at runtime. .dbg captures the records contributed during the
// child's original compile so they can be replayed (with dedup) on hit.
//
// IMPORTANT: any compile option that can change a child object's bytes MUST be
// folded into computeKey(). Today that means enableDebug. If you add a new flag
// that affects code generation (e.g. an optimization level), add it to
// CacheKeyInputs and hash it in computeKey, AND bump CACHE_FORMAT_VERSION.

'use strict';

import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { SymbolEntry, SymbolTable } from './symbolTable';
import { eElementType } from './types';
import { TextLine } from './textLine';

/**
 * Cache format version. Bump whenever:
 *  - the on-disk layout changes (new sidecar file, removed field, etc.)
 *  - the symbol serialization shape changes
 *  - a new compile option is folded into the key
 *
 * Bumping this invalidates every existing cache entry by changing every key.
 * Old <key>.bin files become unreachable and are cleaned by --cache-clear.
 */
export const CACHE_FORMAT_VERSION = 3;

export interface CacheStats {
  hits: number;
  misses: number;
}

export interface CacheMetadata {
  source: string;
  overrides: string;
  compilerVersion: string;
  enableDebug: boolean;
  cacheFormatVersion: number;
  timestamp: number;
  binarySize: number;
  symbolCount: number;
}

export interface CacheKeyInputs {
  preprocessedLines: TextLine[];
  overrides: SymbolTable | undefined;
  compilerVersion: string;
  enableDebug: boolean;
}

export interface CacheStoreOptions {
  metadata?: CacheMetadata;
  symbols?: SymbolEntry[];
  /**
   * Debug records contributed by this child, in the order they were added to
   * the shared DebugData table. Each entry is the raw bytes of one record
   * (including its trailing zero terminator). When provided and non-empty, a
   * .dbg sidecar is written alongside the .bin.
   */
  debugRecords?: Uint8Array[];
}

/** Compact serialized form of a SymbolEntry. Field names kept short to
 *  minimize on-disk size; bigint values are tagged so round-trip is lossless. */
interface SerializedSymbol {
  n: string; // name
  t: number; // type (eElementType)
  v: string | { $b: string }; // value: plain string OR bigint-as-decimal-string
  i?: 1; // isInline (omitted when false)
}

interface SerializedSymFile {
  cacheFormatVersion: number;
  symbols: SerializedSymbol[];
}

interface SerializedDbgFile {
  cacheFormatVersion: number;
  /** Each record's bytes encoded as base64 (including the trailing 0 terminator). */
  records: string[];
}

export class ObjectCache {
  private cacheDir: string;
  private enabled: boolean;
  private _hits: number = 0;
  private _misses: number = 0;

  constructor(enabled: boolean, cacheDir: string = '.pnut-cache') {
    this.enabled = enabled;
    this.cacheDir = path.resolve(cacheDir);
    if (enabled && !fs.existsSync(this.cacheDir)) {
      fs.mkdirSync(this.cacheDir, { recursive: true });
    }
  }

  /** Compute cache key from all inputs that affect the compiled binary. */
  computeKey(inputs: CacheKeyInputs): string {
    const hash = crypto.createHash('sha256');
    // Preprocessed source lines (transitively captures all #include content)
    for (const line of inputs.preprocessedLines) {
      hash.update(line.text);
      hash.update('\n');
    }
    // Sorted parameter overrides
    if (inputs.overrides) {
      const entries = inputs.overrides.allSymbols.slice().sort((a, b) => a.name.localeCompare(b.name));
      for (const sym of entries) {
        hash.update(`${sym.name}:${sym.type}:${sym.value}`);
      }
    }
    // Compile inputs that change generated bytecode
    hash.update(`v:${inputs.compilerVersion}`);
    hash.update(`d:${inputs.enableDebug ? 1 : 0}`);
    hash.update(`f:${CACHE_FORMAT_VERSION}`);
    return hash.digest('hex');
  }

  /** Retrieve a cached binary by key. Returns undefined on miss. */
  get(key: string): Uint8Array | undefined {
    if (!this.enabled) return undefined;
    const binPath = this.binPath(key);
    if (fs.existsSync(binPath)) {
      this._hits++;
      return new Uint8Array(fs.readFileSync(binPath));
    }
    this._misses++;
    return undefined;
  }

  /** Retrieve cached user symbols for a key. Returns undefined if the .sym
   *  sidecar is missing, malformed, or has a mismatched format version. */
  getSymbols(key: string): SymbolEntry[] | undefined {
    if (!this.enabled) return undefined;
    const symPath = this.symPath(key);
    if (!fs.existsSync(symPath)) return undefined;
    try {
      const raw = fs.readFileSync(symPath, 'utf8');
      const parsed = JSON.parse(raw) as SerializedSymFile;
      if (parsed.cacheFormatVersion !== CACHE_FORMAT_VERSION) return undefined;
      if (!Array.isArray(parsed.symbols)) return undefined;
      return deserializeSymbols(parsed.symbols);
    } catch {
      return undefined;
    }
  }

  /** Retrieve cached debug records for a key. Returns undefined if the .dbg
   *  sidecar is missing, malformed, or has a mismatched format version.
   *  Returns an empty array when the child contributed no records (e.g. it
   *  contained no debug() calls, or was cached with --debug off). */
  getDebugRecords(key: string): Uint8Array[] | undefined {
    if (!this.enabled) return undefined;
    const dbgPath = this.dbgPath(key);
    if (!fs.existsSync(dbgPath)) return undefined;
    try {
      const raw = fs.readFileSync(dbgPath, 'utf8');
      const parsed = JSON.parse(raw) as SerializedDbgFile;
      if (parsed.cacheFormatVersion !== CACHE_FORMAT_VERSION) return undefined;
      if (!Array.isArray(parsed.records)) return undefined;
      return parsed.records.map((b64) => new Uint8Array(Buffer.from(b64, 'base64')));
    } catch {
      return undefined;
    }
  }

  /** Store a compiled object in the cache. Writes sidecars first, binary
   *  last, so an interrupted run never leaves a `.bin` without companions. */
  set(key: string, binary: Uint8Array, options: CacheStoreOptions = {}): void {
    if (!this.enabled) return;
    if (!fs.existsSync(this.cacheDir)) {
      fs.mkdirSync(this.cacheDir, { recursive: true });
    }
    if (options.symbols !== undefined) {
      const payload: SerializedSymFile = {
        cacheFormatVersion: CACHE_FORMAT_VERSION,
        symbols: serializeSymbols(options.symbols)
      };
      fs.writeFileSync(this.symPath(key), JSON.stringify(payload));
    }
    if (options.debugRecords !== undefined) {
      const payload: SerializedDbgFile = {
        cacheFormatVersion: CACHE_FORMAT_VERSION,
        records: options.debugRecords.map((rec) => Buffer.from(rec).toString('base64'))
      };
      fs.writeFileSync(this.dbgPath(key), JSON.stringify(payload));
    }
    if (options.metadata !== undefined) {
      fs.writeFileSync(this.metaPath(key), JSON.stringify(options.metadata, null, 2));
    }
    // Binary last — its presence is the cache-hit gate.
    fs.writeFileSync(this.binPath(key), binary);
  }

  /** Remove all cache entries for this directory. */
  clear(): void {
    ObjectCache.clearCacheDir(this.cacheDir);
  }

  /** Remove a given cache directory if it exists. Returns true when removed. */
  static clearCacheDir(cacheDir: string): boolean {
    const resolved = path.resolve(cacheDir);
    if (fs.existsSync(resolved)) {
      fs.rmSync(resolved, { recursive: true });
      return true;
    }
    return false;
  }

  get stats(): CacheStats {
    return { hits: this._hits, misses: this._misses };
  }

  get isEnabled(): boolean {
    return this.enabled;
  }

  get cachePath(): string {
    return this.cacheDir;
  }

  private binPath(key: string): string {
    return path.join(this.cacheDir, `${key}.bin`);
  }

  private symPath(key: string): string {
    return path.join(this.cacheDir, `${key}.sym`);
  }

  private dbgPath(key: string): string {
    return path.join(this.cacheDir, `${key}.dbg`);
  }

  private metaPath(key: string): string {
    return path.join(this.cacheDir, `${key}.meta`);
  }
}

// --- Symbol serialization helpers --------------------------------------------
// SymbolEntry.instanceNumber is a process-global counter used only for sort
// order at construction time and is intentionally NOT preserved across runs.
// MapGenerator does not consult it.

export function serializeSymbols(symbols: SymbolEntry[]): SerializedSymbol[] {
  const out: SerializedSymbol[] = new Array(symbols.length);
  for (let i = 0; i < symbols.length; i++) {
    const s = symbols[i];
    const v: SerializedSymbol['v'] = typeof s.value === 'bigint' ? { $b: s.value.toString() } : s.value;
    const entry: SerializedSymbol = { n: s.name, t: s.type, v };
    if (s.isInline) entry.i = 1;
    out[i] = entry;
  }
  return out;
}

export function deserializeSymbols(serialized: SerializedSymbol[]): SymbolEntry[] {
  const out: SymbolEntry[] = new Array(serialized.length);
  for (let i = 0; i < serialized.length; i++) {
    const s = serialized[i];
    const value: bigint | string = typeof s.v === 'string' ? s.v : BigInt(s.v.$b);
    out[i] = new SymbolEntry(s.n, s.t as eElementType, value, s.i === 1);
  }
  return out;
}
