# ~/.bashrc: executed by bash(1) for non-login shells.

# Note: PS1 and umask are already set in /etc/profile. You should not
# need this unless you want different defaults for root.
# PS1='${debian_chroot:+($debian_chroot)}\h:\w\$ '
# umask 022
set -o vi
export HISTCONTROL=ignoreboth:erasedups
export NODE_OPTIONS="--max-old-space-size=8192" # 8G vs built-in 2G

# You may uncomment the following lines if you want `ls' to be colorized:
export LS_OPTIONS='--color=auto'
eval "$(dircolors)"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias lsf='ls $LS_OPTIONS -F'
# alias l='ls $LS_OPTIONS -lA'
#
# Some more alias to avoid making mistakes:
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'
if [ -f /opt/container-tools/opt/todo-mcp/bin/todo-mcp  ]; then
    export PATH="/opt/container-tools/opt/todo-mcp/bin:$PATH"
fi

# MCP CLI alias
alias myclaude='claude --verbose --mcp-config /opt/container-tools/etc/mcp.json'
