#!/bin/bash
SCRIPT=${0##*/}
SCRIPT_VERSION="1.0"

NEW_TEST_DIR="TEST/ALLCODE-tests"
DIST_DIR="dist"

# Create the target directory if it doesn't exist
(set -x;mkdir -p "${NEW_TEST_DIR}")

# Check if TEST/ALLCODE-tests directory already contains files
if [ "$(ls -A "${NEW_TEST_DIR}")" ]; then
    echo "${SCRIPT}: Abort: ${NEW_TEST_DIR} is already set up!"
    exit 1
fi

# remove compiled tests so they are compiled again
(set -x;rm -rf ${DIST_DIR}/tests)

# Copy all files from the specified source directories to the target directory
# Define a list of directories to copy from
# NOTE: do coverage tests first, so the debug tests overwrite some of them
dirs=("TEST/COV-tests" "TEST/SPIN-tests" "TEST/FLASH-tests" "TEST/LANG-VER-tests" "TEST/OBJ-tests" "TEST/DBG-tests" "TEST/DBG-CROP-tests" "TEST/DAT-PASM-tests" "TEST/VAR-tests" "TEST/CON-tests" "TEST/ENCODING-tests" "TEST/LOADER-tests" "TEST/LANG-FEAT-tests" "TEST/V52A-tests")

# Loop over the list and copy each directory's contents to TEST/ALLCODE-tests
for dir in "${dirs[@]}"; do
    cp "$dir"/* ${NEW_TEST_DIR}
done
# remove prior compilation results before running coverage
rm -f ${NEW_TEST_DIR}/*.bin
rm -f ${NEW_TEST_DIR}/*.lst
rm -f ${NEW_TEST_DIR}/*.obj
rm -f ${NEW_TEST_DIR}/*.elem
rm -f ${NEW_TEST_DIR}/*.elemold
rm -f ${NEW_TEST_DIR}/*.elemORIG
rm -f ${NEW_TEST_DIR}/*.errout
rm -f ${NEW_TEST_DIR}/*.bat
rm -f ${NEW_TEST_DIR}/*.ps1

# Find and rename all *.test.ts files in src/tests to *.test.ts.HOLD
find src/tests -type f -name "*.test.ts" -exec bash -c 'mv "$0" "${0%.test.ts}.test.ts.HOLD"' {} \;

mv src/tests/ALLCODE-tests/pnut-ts-allcode.test.ts.HOLD src/tests/ALLCODE-tests/pnut-ts-allcode.test.ts

# these never move to .HOLD so undo the rename
mv src/tests/EXCEPT-tests/pnut-ts-except.test.ts.HOLD src/tests/EXCEPT-tests/pnut-ts-except.test.ts
mv src/tests/PREPROC-tests/pnut-ts-preproc.test.ts.HOLD src/tests/PREPROC-tests/pnut-ts-preproc.test.ts

num_files=$(find ${NEW_TEST_DIR} -type f -name '*.spin2' | wc -l)
echo "${SCRIPT}: Copied $num_files .spin2 test files to ${NEW_TEST_DIR}"
